// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mottu_DOTNET.src.Infrastructure.Data;

#nullable disable

namespace Mottu_DOTNET.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250908222343_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mottu_DOTNET.src.Domain.Entities.Moto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PatioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.ToTable("Motos");
                });

            modelBuilder.Entity("Mottu_DOTNET.src.Domain.Entities.Patio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patios");
                });

            modelBuilder.Entity("Mottu_DOTNET.src.Domain.Entities.Moto", b =>
                {
                    b.HasOne("Mottu_DOTNET.src.Domain.Entities.Patio", null)
                        .WithMany("Motos")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Mottu_DOTNET.src.Domain.ValueObjects.Placa", "Placa", b1 =>
                        {
                            b1.Property<Guid>("MotoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Placa");

                            b1.HasKey("MotoId");

                            b1.ToTable("Motos");

                            b1.WithOwner()
                                .HasForeignKey("MotoId");
                        });

                    b.OwnsOne("Mottu_DOTNET.src.Domain.ValueObjects.Posicao", "Posicao", b1 =>
                        {
                            b1.Property<Guid>("MotoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Posicao");

                            b1.HasKey("MotoId");

                            b1.ToTable("Motos");

                            b1.WithOwner()
                                .HasForeignKey("MotoId");
                        });

                    b.Navigation("Placa")
                        .IsRequired();

                    b.Navigation("Posicao")
                        .IsRequired();
                });

            modelBuilder.Entity("Mottu_DOTNET.src.Domain.Entities.Patio", b =>
                {
                    b.Navigation("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
